name: Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Roda outro comando!
        run: echo $(ls)
